creating Issue log works now, You can test it on issue detail
kh-004-webuipython/Jiller pull request #131
Opened 2017-02-10 18:18 UTC by VitaliiSypchenko

2017-02-10 18:56 UTC, italamanova approved these changes

2017-02-10 23:33 UTC, Phobos-Programmer reviewed
Убери console.log(data); и сделай 1 миграцию в емплое заместо 4х

2017-02-12 15:25 UTC, belokongunner requested changes
миграций по-прежнему куча в реквесте, перезапусти или удали локально и перекомить
 project/views.py строка 340 нет проверки на существование активного спринта

2017-02-14 11:56 UTC, belokongunner approved these changes

2017-02-14 11:56 UTC, merged