Sprint feedbacks and releases
kh-004-webuipython/Jiller pull request #134
Opened 2017-02-11 15:05 UTC by Phobos-Programmer

2017-02-11 15:13 UTC, Phobos-Programmer commented
Хоть ветка и посвящена фидбекам и релизу, на текущем этапе тут реализовано перетягивание в активном спринте и подправлен init JSON (доступ RU девелоперам на ишью и запрет на СU спринтов)

2017-02-11 15:54 UTC, VitaliiSypchenko commented on project/views.py
> +            if sprint.status == 'active' and (table == Issue.IN_PROGRESS or
красивее записать table in (values):

2017-02-12 16:30 UTC, belokongunner requested changes
Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

2017-02-12 22:18 UTC, italamanova approved these changes

2017-02-13 10:27 UTC, belokongunner approved these changes

2017-02-13 10:27 UTC, merged