Created issues_search template; Added new tab 'Issues' to project_nav…
kh-004-webuipython/Jiller pull request #137
Opened 2017-02-12 21:06 UTC by Norfolks

…bar template; Renamed BacklogTable to IssuesTable; Created new url to urls; Added new class IssuesSearchView.

2017-02-12 22:08 UTC, Phobos-Programmer approved these changes

2017-02-13 08:21 UTC, egepsihora approved these changes

2017-02-13 21:52 UTC, belokongunner requested changes

2017-02-13 21:52 UTC, belokongunner commented on project/templates/project/project_navbar.html
> +    <li {% if issues %}class="active" {% endif %}>
class="active" убери

2017-02-13 22:00 UTC, belokongunner requested changes
Тесты + project/view.py конфликт маленький по импорту таблиц, спулься

2017-02-14 18:38 UTC, belokongunner approved these changes

2017-02-14 18:38 UTC, merged