Home page refactored
kh-004-webuipython/Jiller pull request #149
Opened 2017-02-16 19:52 UTC by VitaliiSypchenko

2017-02-16 21:15 UTC, belokongunner approved these changes

2017-02-16 21:45 UTC, Phobos-Programmer approved these changes

2017-02-16 21:50 UTC, italamanova requested changes
При логине вылетает ошибка:
NoReverseMatch at /login/
Reverse for 'profile' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

2017-02-16 23:26 UTC, Phobos-Programmer approved these changes

2017-02-17 12:52 UTC, italamanova approved these changes

2017-02-17 12:52 UTC, merged