Twitter
kh-004-webuipython/Jiller pull request #154
Opened 2017-02-17 18:40 UTC by Phobos-Programmer

2017-02-17 20:32 UTC, VitaliiSypchenko commented on project/templates/project/sprint_detail.html
> +      {% if object.feedback_text %}
почему это не обьеденить в один if?

2017-02-17 20:32 UTC, VitaliiSypchenko commented on project/views.py
> +                    get_object_or_404(ProjectNote, pk=note.id)
для чего ты достаешь обьект, это ты проверку так делаешь?

2017-02-17 20:32 UTC, VitaliiSypchenko commented on project/views.py
> -            raise Http404("Wrong request")
почему 404?

2017-02-17 20:32 UTC, VitaliiSypchenko commented on project/views.py
> +            form = NoteForm(request.POST)
как эта форма отдает ошибки?

2017-02-17 20:32 UTC, VitaliiSypchenko commented on project/views.py
>                      return HttpResponse()
почему ты отдаешь пустой респонс?

2017-02-17 20:32 UTC, VitaliiSypchenko commented on project/views.py
>          if 'id' in request.POST and 'title' in request.POST and 'content' \
вот этого проверять не нужно, если эти параметры обязательные и их не передали, то естественно форма будет не валидна

2017-02-17 21:47 UTC, Phobos-Programmer commented on project/templates/project/sprint_detail.html
> +      {% if object.feedback_text %}
потому что у нас может спринт останавливаться, в перспективе,  и тогда не будет линка

2017-02-17 22:43 UTC, italamanova approved these changes

2017-02-17 22:54 UTC, Norfolks requested changes

2017-02-17 22:54 UTC, Norfolks commented on project/views.py
>  @waffle_flag('only_developer')
Договарились же дать доступ всем

2017-02-17 23:08 UTC, Norfolks commented
Почему ветка реквеста называется twitter?
Тут же нет ничего связанного с социальными кнопками.

2017-02-17 23:26 UTC, VitaliiSypchenko commented on project/templates/project/sprint_detail.html
> +      {% if object.feedback_text %}
Но они дублируют друг друга

2017-02-18 08:48 UTC, Norfolks approved these changes
Нового функционала не увидел
Если он не связан с ноутами его не надо было кидать
Ибо сейчас хрен найдёшь что =/

2017-02-18 09:31 UTC, VitaliiSypchenko commented on project/views.py
>              id = request.POST.get('id')
id это зарезервированое имя в питоне, переопределив его ты не сможешь вызвать функцию id(), я конечно понимаю что эта функция тебе не нужна, но это просто плохая практика

2017-02-18 09:31 UTC, VitaliiSypchenko commented on project/views.py
> +            if id == 'undefined':
Странно выглядит, если у тебя в js айдишник пришел undefined просто не передавай его. ТЫ же когда пишешь форму, и например в этой форме какие-то поля не обязательные, тебе не приходит на бэкенд undefined, тебе просто это значение не приходит.
Если я неправильно понял ситуацию, обьясни

2017-02-18 09:31 UTC, VitaliiSypchenko commented on project/views.py
>                  response.__setitem__('note_id', str(note.id))
Таким образом ты на фронт отправляешь данные?
Ты в js обращаешься к request.note_id?

2017-02-18 12:57 UTC, VitaliiSypchenko commented on project/static/project/js/push_issue_in_active_sprint.js
>          xhr.open("POST", '/project/issue_push/', true);
захардкодженная урла, лучше использовать функцию  реверс для генерации урлы, как и договаривались

2017-02-18 12:57 UTC, VitaliiSypchenko commented on project/templates/project/notes.html
> +                  maxlength='25' rows='1'>{{ note.title }}</textarea>
Я чтото запутался, ты написал джанго форму но не используешь её в контексте

2017-02-18 15:03 UTC, egepsihora approved these changes

2017-02-18 19:44 UTC, merged