auth with github
kh-004-webuipython/Jiller pull request #160
Opened 2017-02-19 12:54 UTC by VitaliiSypchenko

Авторизация при помощи github
Иcпользовал либу django-allauth

2017-02-19 22:11 UTC, italamanova commented
django.db.migrations.exceptions.NodeNotFoundError: Migration project.0008_merge_20170219_1009 dependencies reference nonexistent parent node (u'project', u'0006_auto_20170218_1750')

2017-02-20 18:23 UTC, Phobos-Programmer requested changes
Блин, сравненивал с мастером. Ща с миграциями все ок?

2017-02-20 18:23 UTC, Phobos-Programmer commented on Jiller/settings.py
> +    # 'Jiller.middleware.LoginRequiredMiddleware.LoginRequiredMiddleware',
Jiller.middleware

2017-02-20 18:25 UTC, Phobos-Programmer approved these changes

2017-02-20 20:25 UTC, italamanova approved these changes

2017-02-20 20:52 UTC, merged