large refactoring of full project
kh-004-webuipython/Jiller pull request #53
Opened 2017-01-27 18:11 UTC by VitaliiSypchenko

Оставляйте комментарии прям в комите, будем вместе решать что ок а что нетю
П.С. мне местами пришлось затронуть исходный код, не обижайтесь

2017-01-27 19:55 UTC, ghost submitted a review, later dismissed

2017-01-27 22:32 UTC, Norfolks requested changes

2017-01-27 22:32 UTC, Norfolks commented on general/urls.py
> +    url(r'^profile/$', views.profile_view, name='profile'),
Profile it is employee information. It is shouldn't be there.

2017-01-27 22:32 UTC, Norfolks commented on project/templates/project/backlog.html
> +{% load i18n %}
What is this?

2017-01-27 22:32 UTC, Norfolks commented on employee/templates/employee/detail.html
>  {% block breadcrumbs %}
What is this?

2017-01-27 23:16 UTC, italamanova approved these changes

2017-01-28 12:43 UTC, Norfolks approved these changes

2017-01-30 15:19 UTC, closed without merging